### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by norkator** [Maiska123/Fullstack-Edible-Battle#4]
💩

**Comment by Maiska123** [comment]
no you.

**Comment by norkator** [comment]
> no you.

🤪

**Comment by Maiska123** [comment]
> > no you.
> 
> 🤪

I see, i found the issue now....


ITS YOU! 👀

**Comment by norkator** [comment]
> > > no you.
> > 
> > 
> > 🤪
> 
> I see, i found the issue now....
> 
> ITS YOU! 👀

No, you are the problem 😉😉😉

**Comment by norkator** [comment]
@Maiska123 @Maiska123 @Maiska123 
![image](https://user-images.githubusercontent.com/55850510/203646287-7cd273a0-b3cb-4f56-b5d6-97ec42fc2cc2.png)
